version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - ./.env.develop
    volumes:
      - .:/app
    command: pnpm start:dev -b swc --preserveWatchOutput
  
  postgres-db:
    image: postgres:13
    restart: always
    env_file:
      - ./.env.develop
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
